/*
Enum for application setting key
 */
export enum ApplicationSettingKeyEnum {
  DUPLICATE_LOGIN_PREVENTION = 'DUPLICATE_LOGIN_PREVENTION',
  SIGN_UP_RESTRICTION = 'SIGN_UP_RESTRICTION',
  UPLOAD_THUMBNAIL_IMAGE_SIZE_LIMIT = 'UPLOAD_THUMBNAIL_IMAGE_SIZE_LIMIT',
  UPLOAD_PROFILE_IMAGE_SIZE_LIMIT = 'UPLOAD_PROFILE_IMAGE_SIZE_LIMIT',
  USER_STORAGE_LIMIT = 'USER_STORAGE_LIMIT',
}
